version: '3.3'

services:
  db:
    image: mariadb:latest
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rmon_network
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: rmon
      MARIADB_USER: rmon
      MARIADB_PASSWORD: rmon

  netsnmp:
    image: jslarraz/netsnmp:latest
    networks:
      - rmon_network
    restart: always
    environment:
      RO_COMMUNITY: public
      RW_COMMUNITY: private

  rmon:
    depends_on:
      - db
      - netsnmp
    build: .
    networks:
      - rmon_network
    ports:
      - "161:161/udp"
    restart: always
    environment:
      MARIADB_HOST: db:3306
      MARIADB_DATABASE: rmon
      MARIADB_USER: rmon
      MARIADB_NAME: rmon
      NETSNMP_HOST: netsnmp:161
      NETSNMP_RO_COMMUNITY: public
      NETSNMPRW_COMMUNITY: private
      RMON_HOST: 0.0.0.0/161
      RMON_MAX_FILTERS: 50

volumes:
    db_data: {}

networks:
  rmon_network:
