version: '3.3'

services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rmon_network
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: rmon
      MARIADB_USER: rmon
      MARIADB_PASSWORD: rmon

  rmon:
    depends_on:
      - db
    build: .
    command: bash -c "snmpd && python agentV3_r1.py"
    networks:
      - rmon_network
    ports:
      - "161:161/udp"
    restart: always
    environment:
      MARIADB_HOST: db
      MARIADB_DATABASE: rmon
      MARIADB_USER: rmon
      MARIADB_NAME: rmon
      NETSNMP_HOST: localhost:162
      NETSNMP_COMMUNITY: public
      RMON_HOST: 0.0.0.0/161
      RMON_MAX_FILTERS: 50

volumes:
    db_data: {}

networks:
  rmon_network:
