version: '3.3'

services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/rmon-db-root
      MARIADB_DATABASE_FILE: /run/secrets/rmon-db-name
      MARIADB_USER_FILE: /run/secrets/rmon-db-user
      MARIADB_PASSWORD_FILE: /run/secrets/rmon-db-pass

  netsnmp:
    image: sastre3/netsnmp:latest
    restart: always
    environment:
      RO_COMMUNITY_FILE: /run/secrets/rmon-ro-community
      RW_COMMUNITY_FILE: /run/secrets/rmon-rw_community

  wordpress:
    depends_on:
      - db
      - netsnmp
    build: .
    ports:
      - "161:161"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      RO_COMMUNITY_FILE:
      RW_COMMUNITY_FILE:
      RMON_HOST:
      RO_COMMUNITY_FILE
volumes:
    db_data: {}